[package]
name = "gym_verify"
type = "bin"
version = "0.1.0"
authors = ["DeGym Team"]
description = "Circuito para verificação de presença em academias"

[dependencies]
noir_stdlib = { tag = "v0.1.0", git = "https://github.com/noir-lang/noir" }
