[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
taraxa_testnet = "${TARAXA_RPC_URL}"
zkverify_testnet = "${ZKVERIFY_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
taraxa_testnet = { key = "${ETHERSCAN_API_KEY}" }
zkverify_testnet = { key = "${ETHERSCAN_API_KEY}" }

# Configurações específicas para cada rede
[profile.taraxa]
eth_rpc_url = "${TARAXA_RPC_URL}"

[profile.zkverify]
eth_rpc_url = "${ZKVERIFY_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
